name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
        working_directory: docs
      - run: npm run build
        working_directory: docs
      - uses: untitaker/hyperlink@0.1.32
        with:
          args: docs/_site/
  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx run pre-commit run --all-files
  run-pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - 3.x
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
          check-latest: true
      - run: poetry install --sync --no-root --no-interaction
      - run: poetry run --no-interaction pytest
