name: Linkcheck
on: [push]
jobs:
  linkcheck:
    name: Linkcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: npm install, build
      run: |
        cd docs
        npm install
        npm run build

    - uses: untitaker/hyperlink@0.1.32
      with:
        args: docs/_site/
