name: Publish
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  build-compiled:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-2025
          - macos-13
          - macos-15
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
      - run: uv tool run --from cibuildwheel@latest --no-cache --python 3.13 cibuildwheel --output-dir dist
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist
  build-pure:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
      - run: uv build --python 3.13 --no-cache
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-any
          path: dist
  publish-pypi:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'djlint' && startsWith(github.ref, 'refs/tags/')  }}
    needs:
      - build-compiled
      - build-pure
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
      - run: mkdir dist
      - run: mv wheels-*/* dist
      - uses: pypa/gh-action-pypi-publish@release/v1
  publish-npm:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'djlint' && startsWith(github.ref, 'refs/tags/')  }}
    needs:
      - publish-pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
