name: Publish
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  build-compiled:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-13
          - macos-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv tool run --from cibuildwheel@latest --no-cache --python 3.12 cibuildwheel --output-dir dist
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist
  build-pure:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'djlint' }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv build --python 3.12 --no-cache
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-any
          path: dist
  publish-pypi:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'djlint' && startsWith(github.ref, 'refs/tags/')  }}
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
      - uses: pypa/gh-action-pypi-publish@release/v1
  publish-npm:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'djlint' && startsWith(github.ref, 'refs/tags/')  }}
    needs:
      - build-compiled
      - build-pure
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
